original = input("What's your full name? ")
print(f"Original   : {original}")
upper = original.upper()
print(f"Uppercase  : {upper}")
lower = original.lower()
print(f"Lowercase  : {lower}")
title = original.title()
print(f"Title Case : {title}")
length = len(original)
print(f"Length     : {length}")